language: python

python:
  "2.7"


install:
    - "pip install -r dev-requirements.txt"


script:
    - bash tools/pep8.sh
    - bash tools/lint.sh
    - bash tools/test.sh


branches:
  only:
    - master


notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      cloud4rpi:SLACK_TOKEN#builds
