language: python

python:
  "2.7"


install:
    - "pip install -r requirements.txt"
    - "pip install -r dev-requirements.txt"


script:
    - bash tools/lint.sh
    - bash tools/test.sh


branches:
  only:
    - travis


notifications:
  slack:
    rooms:
      cloud4rpi:VenN0n5LbRGi25ACnHUSmgUu#builds
